FROM openjdk:17-jdk-alpine
MAINTAINER xgeorget.dev
WORKDIR /app

ARG DATABASE_HOST=${DATABASE_HOST}
ENV DATABASE_HOST=${DATABASE_HOST}
ARG DATABASE_PORT=${DATABASE_PORT}
ENV DATABASE_PORT=${DATABASE_PORT}
ARG DATABASE_USERNAME=${DATABASE_USERNAME}
ENV DATABASE_USERNAME=${DATABASE_USERNAME}
ARG DATABASE_PASSWORD=${DATABASE_PASSWORD}
ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}
ARG DATABASE_NAME=${DATABASE_NAME}
ENV DATABASE_NAME=${DATABASE_NAME}

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src

RUN ./mvnw clean package -DskipTests

ENTRYPOINT ["java", "-jar", "/app/target/*.jar"]